name: "\U0001F680 Feature request"
description: Submit a request for a new Open-AutoGLM / 鎻愪氦涓€涓柊鐨?Open-AutoGLM 鐨勫姛鑳藉缓璁?
labels: [ "feature" ]
body:
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature request  / 鍔熻兘寤鸿
      description: |
        A brief description of the functional proposal. Links to corresponding papers and code are desirable.
        瀵瑰姛鑳藉缓璁殑绠€杩般€傛渶濂芥彁渚涘搴旂殑璁烘枃鍜屼唬鐮侀摼鎺?

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation / 鍔ㄦ満
      description: |
        Your motivation for making the suggestion. If that motivation is related to another GitHub issue, link to it here.
        鎮ㄦ彁鍑哄缓璁殑鍔ㄦ満銆傚鏋滆鍔ㄦ満涓庡彟涓€涓?GitHub 闂鏈夊叧锛岃鍦ㄦ澶勬彁渚涘搴旂殑閾炬帴銆?

  - type: textarea
    id: contribution
    validations:
      required: true
    attributes:
      label: Your contribution / 鎮ㄧ殑璐＄尞
      description: |

        Your PR link or any other link you can help with.
        鎮ㄧ殑PR閾炬帴鎴栬€呭叾浠栨偍鑳芥彁渚涘府鍔╃殑閾炬帴銆?
